name: 'Code quality'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  lint:
    name: '/'
    uses: technology-studio/github-workflows/.github/workflows/_code-style.yml@main
