name: "PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: '/'
    uses: technology-studio/github-workflows/.github/workflows/_pr.yml@main
