name: 'PR'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  semantic-title:
    name: 'Semantic title'
    uses: technology-studio/github-workflows/.github/workflows/_semantic-title.yml@696ee6d68a8fdb357c5a6e26e748fba32f09a9bb # main
    secrets: inherit
