name: Release
on:
  push:
    branches:
      - main
      - next
      - next-major
      - alpha
      - beta

jobs:
  release:
    name: '/'
    uses: technology-studio/github-workflows/.github/workflows/_release.yml@main
    secrets: inherit
