name: Resolve yarn.lock

on:
  issue_comment:
    types: [created]

jobs:
  resolve-yarn-lock-on-comment:
    if: contains(github.event.comment.body, '/resolve yarn.lock')
    uses: technology-studio/github-workflows/.github/workflows/resolve-yarn-lock.yml@main
    with:
      pr-number: ${{ github.event.issue.number }}
      repo: ${{ github.repository }}
