name: 'Test'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read
  id-token: write

jobs:
  unit:
    name: 'Unit test'
    uses: technology-studio/github-workflows/.github/workflows/_unit-test.yml@45c6d0da456aff0525690d86cac745bc75a96a85 # main
    secrets: inherit
