name: 'Test'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  unit:
    name: 'Unit test'
    uses: technology-studio/github-workflows/.github/workflows/_unit-test.yml@696ee6d68a8fdb357c5a6e26e748fba32f09a9bb # main
    secrets: inherit
